dnsimple/dnsimple-csharp

CHANGELOG.md
src/dnsimple-test/Services/RegistrarTest.cs
src/dnsimple/Services/Registrar.cs

Premium price field will be deprecated in the API, so we should remove
it from the response. This commit changes the TransferDomain method to
accept a new model called DomainTransferInput that contains only the
needed attributes to make the request and remove the PremiumPrice from
the DomainTransfer model that will be responded from the method.

Remove PremiumPrice from DomainTransfer response

---

src/dnsimple-test/Services/DomainsTest.cs
src/dnsimple-test/Services/RegistrarTest.cs
src/dnsimple-test/fixtures/v2/api/cancelDomainTransfer/success.http
src/dnsimple-test/fixtures/v2/api/createDomain/created.http
src/dnsimple-test/fixtures/v2/api/getDomain/success.http
src/dnsimple-test/fixtures/v2/api/getDomainTransfer/success.http
src/dnsimple-test/fixtures/v2/api/listDomains/success.http
src/dnsimple-test/fixtures/v2/webhooks/domain.auto_renewal_disable/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.auto_renewal_enable/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.create/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.delegation_change/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.delete/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.register/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.register/status-started.http
src/dnsimple-test/fixtures/v2/webhooks/domain.registrant_change/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.renew/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.resolution_disable/example.http
src/dnsimple-test/fixtures/v2/webhooks/domain.resolution_enable/example.http
src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.disable/example.http
src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.enable/example.http
src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.purchase/example.http
src/dnsimple-test/fixtures/v2/webhooks/whois_privacy.renew/example.http
src/dnsimple/Services/Domains.cs
src/dnsimple/Services/ListOptions/DomainListOptions.cs

This commit deprecates ExpiresOn in favor of ExpiresAt. It also updates
our outdated fixtures.

Include ExpiresAt in Domain object in favor of ExpiresOn

---

src/dnsimple-test/Services/CertificatesTest.cs
src/dnsimple-test/Services/DomainsTest.cs
src/dnsimple-test/fixtures/v2/api/getCertificate/success.http
src/dnsimple-test/fixtures/v2/api/issueLetsencryptCertificate/success.http
src/dnsimple-test/fixtures/v2/api/issueRenewalLetsencryptCertificate/success.http
src/dnsimple-test/fixtures/v2/api/listCertificates/success.http
src/dnsimple-test/fixtures/v2/api/purchaseLetsencryptCertificate/success.http
src/dnsimple-test/fixtures/v2/api/purchaseRenewalLetsencryptCertificate/success.http
src/dnsimple-test/fixtures/v2/webhooks/certificate.issue/example.http
src/dnsimple-test/fixtures/v2/webhooks/certificate.remove_private_key/example.http
src/dnsimple/Services/Certificates.cs
src/dnsimple/Services/Domains.cs
src/dnsimple/Services/ListOptions/CertificatesListOptions.cs

We deprecated expiresOn attribute in our documentation in favor of
expiresAt. This commit introduces the new field and deprecates the old
one. It also updates to use the new fixtures.

Remove Certificate and Domain expiresOn and add Certificate expiresAt

---

CHANGELOG.md

We removed Domain and Certificate ExpiresOn attribute in favor of
ExpiresAt. This commit add the missing Changelog entries for this
information.

Update CHANGELOG for recently introduced ExpiresAt

---

CHANGELOG.md
src/dnsimple-test/Services/ContactsTest.cs
src/dnsimple/Services/Contacts.cs

As said in https://developer.dnsimple.com/v2/contacts/#createContact, Fax field is not required to create a Contact.

Removes required Fax on Contact creation

---

src/dnsimple-test/Services/CertificatesTest.cs
src/dnsimple/Services/Certificates.cs

This PR removes the deprecated `Name` property from the `Certificate` data class
This should be considered a breaking change, although we could argue that in this client's case, it could be safe to ship without bumping the major version. If this is not acceptable, we should change this PR to deprecate the property instead.

Remove the deprecated Name field from the Certificate data class

---

src/dnsimple-test/ClientTest.cs
src/dnsimple/DNSimple.cs

Fixes #21 
Avoids setting UserAgent on ChangeBaseUrlTo if Client is provided with a RestClientWrapper
We should release this as a patch once merged.

Avoids setting UserAgent on ChangeBaseUrlTo when using 

---

src/dnsimple/Services/ZoneRecords.cs

Closes https://github.com/dnsimple/dnsimple-csharp/pull/31 (as it is based on it)
CDNSKEY & CDS record types are missing from the ZoneRecordType enum. This PR adds them.
Co-Authored-By: Geert Van Huychem <geert@exira.com> Thanks @VanHuychemG! ❤️

Adds missing CDNSKEY & CDS record types

---

src/dnsimple/Services/Http.cs

BadRequest response without "errors" present, should also be handled here, otherwise the deserialization ("data") fails further down the process.

Handle BadRequest without "errors"

---

CHANGELOG.md
CONTRIBUTING.md
README.md
src/dnsimple/dnsimple.nuspec

This PR accommodates documentation and links to the corresponding new `main` default branch
Blocked by the actual task of renaming this repo default branch to `main`

Moves documentation to `main` branch

---

src/dnsimple-test/Services/DomainsDelegationSignerRecordsTest.cs
src/dnsimple-test/Services/TldsTest.cs
src/dnsimple-test/fixtures/v2/api/createDelegationSignerRecord/created.http
src/dnsimple-test/fixtures/v2/api/getDelegationSignerRecord/success.http
src/dnsimple-test/fixtures/v2/api/getTld/success.http
src/dnsimple-test/fixtures/v2/api/listDelegationSignerRecords/success.http
src/dnsimple-test/fixtures/v2/api/listTlds/success.http
src/dnsimple/Services/DomainsDelegationSignerRecords.cs
src/dnsimple/Services/Tlds.cs

This PR:
* Updates the fixtures from [dnsimple-developer repo](https://github.com/dnsimple/dnsimple-developer/tree/main/fixtures/v2/api) to reflect the latest changes to our DNSSEC-related APIs.
* Adds new fields to affected structs/DTOs.
* Updates option validation on affected endpoints.
* Completes specs on `GetDelegationSignerRecord` method to be able to test the addition of `PublicKey`.

Add support for key-data interface creating delegation signer records

---

.github/workflows/release.yml
CONTRIBUTING.md

Adds the automated release workflow.
When a new tag is pushed the release workflow will pick it up and start the releasing of the new version.
Things that need to be done (configuration wise), which I have no access to (we need someone with admin rights on this repo for that):

Automate release process

---

src/dnsimple/RequestBuilder.cs
src/dnsimple/Services/RegistrarDelegation.cs

Add JSON payload method without serialization first to prevent string arrays/list being escaped in the request.

Add JSON payload without serialization

---

src/dnsimple-test/Services/CertificatesTest.cs
src/dnsimple/Services/Certificates.cs

We are flagging 2 attributes as deprecated/obsolete:
- `LetsencryptCertificateAttributes.ContactId`
- `Certificate.ContactId`
Note that `LetsencryptCertificateAttributes.ContactId` is flagged as optional/nullable so it can be ignored when purchasing the certificate already (which was wrong, but is now correct):
https://github.com/dnsimple/dnsimple-csharp/blob/5ce5453bdf3d93f554464feceeaa1056f5ec5b4a/src/dnsimple/Services/Certificates.cs#L190

No longer require `contact_id` to purchase LetsEncrypt certificates

---

.tool-versions
src/dnsimple-test/Services/RegistrarTest.cs
src/dnsimple-test/dnsimple-test.csproj
src/dnsimple-test/fixtures/v2/api/getDomainRegistration/success.http
src/dnsimple-test/fixtures/v2/api/getDomainRenewal/success.http
src/dnsimple/Services/Paths.cs
src/dnsimple/Services/Registrar.cs

Recently we introduced two new endpoints (https://github.com/dnsimple/dnsimple-developer/pull/457) in our API for users to retrieve their domain registration and renewal service objects.
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1674

Implement getDomainRenewal and getDomainRegistration endpoints

---

CHANGELOG.md
src/dnsimple-test/Services/DomainsEmailForwardsTest.cs
src/dnsimple-test/Services/ZonesTest.cs
src/dnsimple-test/dnsimple-test.csproj
src/dnsimple-test/fixtures/v2/api/activateZoneService/success.http
src/dnsimple-test/fixtures/v2/api/deactivateZoneService/success.http
src/dnsimple/Services/DomainsEmailForwards.cs
src/dnsimple/Services/Paths.cs
src/dnsimple/Services/Zones.cs

This PR implements https://github.com/dnsimple/dnsimple-developer/pull/502 which allows for the management of DNS resolution for a particular zone.
This PR also updates the `EmailForward` with new attributes replacing `To` and `From` for email forward resource creation. See the changelog for more information.
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/3
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/2

Add support to activate and deactivate DNS services for a zone

---

CHANGELOG.md
src/dnsimple-test/Services/ZonesTest.cs
src/dnsimple-test/fixtures/v2/api/getZone/success.http
src/dnsimple-test/fixtures/v2/api/listZones/success.http
src/dnsimple/Services/Zones.cs

This PR adds [missing attributes](https://github.com/dnsimple/dnsimple-developer/pull/542) of the Zone response:
- `Secondary`, `LastTransferredAt`, `Active` to Zone struct
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/17

Add missing attributes to the Zone API responses

---

CHANGELOG.md
src/dnsimple-test/FixtureLoader.cs
src/dnsimple-test/MockDnsimpleClient.cs
src/dnsimple-test/Services/RegistrarTest.cs
src/dnsimple-test/dnsimple-test.csproj
src/dnsimple-test/fixtures/v2/api/checkRegistrantChange/error-contactnotfound.http
src/dnsimple-test/fixtures/v2/api/checkRegistrantChange/error-domainnotfound.http
src/dnsimple-test/fixtures/v2/api/checkRegistrantChange/success.http
src/dnsimple-test/fixtures/v2/api/createRegistrantChange/success.http
src/dnsimple-test/fixtures/v2/api/deleteRegistrantChange/success.http
src/dnsimple-test/fixtures/v2/api/deleteRegistrantChange/success_async.http
src/dnsimple-test/fixtures/v2/api/getRegistrantChange/success.http
src/dnsimple-test/fixtures/v2/api/listRegistrantChanges/success.http
src/dnsimple/Services/ListOptions/ListRegistrantChangesOptions.cs
src/dnsimple/Services/Paths.cs
src/dnsimple/Services/Registrar.cs
src/dnsimple/Services/ServiceBase.cs

This PR introduces 5 new endpoints that are part of the domain contact management API that was introduced in https://github.com/dnsimple/dnsimple-developer/pull/501.
The following endpoints have been added:
- **listRegistrantChanges**: GET `/{account}/registrar/registrant_changes`
- **createRegistrantChange**: POST `/{account}/registrar/registrant_changes`
- **checkRegistrantChange**: POST `/{account}/registrar/registrant_changes/check`
- **getRegistrantChange**: GET `/{account}/registrar/registrant_changes/{registrantchange}`
- **deleteRegistrantChange**: DELETE `/{account}/registrar/registrant_changes/{registrantchange}`
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1729
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/18

Domain contact management API

---

CHANGELOG.md
src/dnsimple-test/Services/RegistrarTransferLockTest.cs
src/dnsimple-test/dnsimple-test.csproj
src/dnsimple-test/fixtures/v2/api/disableDomainTransferLock/success.http
src/dnsimple-test/fixtures/v2/api/enableDomainTransferLock/success.http
src/dnsimple-test/fixtures/v2/api/getDomainTransferLock/success.http
src/dnsimple/Services/Paths.cs
src/dnsimple/Services/RegistrarTransferLock.cs

This PR introduces 3 new endpoints that are part of the domain transfer lock API that is introduced in https://github.com/dnsimple/dnsimple-developer/pull/519.
The following endpoints have been added:
- **getDomainTransferLock**: GET `/{account}/registrar/domains/{domain}/transfer_lock`
- **enableDomainTransferLock**: POST `/{account}/registrar/domains/{domain}/transfer_lock`
- **disableDomainTransferLock**: DELETE `/{account}/registrar/domains/{domain}/transfer_lock`
Belongs to https://github.com/dnsimple/dnsimple-business/issues/1728
Belongs to https://github.com/dnsimple/dnsimple-external-integrations/issues/18

Domain transfer lock API

---

.github/workflows/ci.yml
.tool-versions
CHANGELOG.md
CONTRIBUTING.md
README.md
src/dnsimple-test/dnsimple-test.csproj
src/dnsimple/Services/DomainsCollaborators.cs

The changes to go out in the next version (0.19.0) are:
- CHANGED: Bumped `dotnet` to `9.0`
- NEW: Added `AliasEmail` to `EmailForward`
- CHANGED: Deprecated `From` and `To` fields in `EmailForward`
- CHANGED: `DomainCollaborators` have been deprecated and will be removed in the next major version. Please use our Domain Access Control feature.
- HOUSEKEEPING: #152
- HOUSEKEEPING: #153
Belongs to https://github.com/dnsimple/dnsimple-engineering/issues/231

Patch cycle - 2024 / Cycle 5

---

CHANGELOG.md
LICENSE.txt
README.md
src/dnsimple/dnsimple.csproj

The changes to go out in the next version (0.19.1) are:
- HOUSEKEEPING: Bump NUnit3TestAdapter from 4.5.0 to 5.0.0 (#165)
- HOUSEKEEPING: Bump Microsoft.NET.Test.Sdk and Newtonsoft.Json (#164)
- HOUSEKEEPING: Bump NUnit.Analyzers from 4.4.0 to 4.6.0 (#163)
- HOUSEKEEPING: Bump nosborn/github-action-markdown-cli from 3.3.0 to 3.4.0 (#162)
- HOUSEKEEPING: Bump Moq from 4.20.70 to 4.20.72 (#160)
- HOUSEKEEPING: Bump nunit from 4.1.0 to 4.3.2 (#156)
Belongs to https://github.com/dnsimple/dnsimple-engineering/issues/295
Part of https://github.com/dnsimple/dnsimple-engineering/issues/294

Patch cycle - 2025 / Cycle 2
